# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0012_auto_20150228_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='nombre_votes_1',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='nombre_votes_2',
        ),
        migrations.AddField(
            model_name='votant',
            name='a_vote',
            field=models.BooleanField(default=False, verbose_name='A voté'),
        ),
        migrations.AddField(
            model_name='votant',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
